/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jockeyracing;

/**
 *
 * @author aluno
 */
public class TelaPista extends javax.swing.JFrame {

    /**
     * Creates new form ThreadJockey
     */
    public TelaPista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpainel1 = new javax.swing.JPanel();
        labelCavalo1 = new javax.swing.JLabel();
        labelCavalo2 = new javax.swing.JLabel();
        labelCavalo3 = new javax.swing.JLabel();
        labelCavalo4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpainel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCavalo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jo1.png"))); // NOI18N
        jpainel1.add(labelCavalo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        labelCavalo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jo2.png"))); // NOI18N
        jpainel1.add(labelCavalo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        labelCavalo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jo3.png"))); // NOI18N
        jpainel1.add(labelCavalo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        labelCavalo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jo4.png"))); // NOI18N
        jpainel1.add(labelCavalo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpainel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 40));

        labelPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arena.png"))); // NOI18N
        jpainel1.add(labelPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        ThreadJockey t1 = new ThreadJockey( labelCavalo1, this, 1);
        ThreadJockey t2 = new ThreadJockey( labelCavalo2, this, 2);
        ThreadJockey t3 = new ThreadJockey( labelCavalo3, this, 3);
        ThreadJockey t4 = new ThreadJockey( labelCavalo4, this, 4);
        
        t1.start();
        t2.start();
        t3.start();
        t4.start();



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpainel1;
    private javax.swing.JLabel labelCavalo1;
    private javax.swing.JLabel labelCavalo2;
    private javax.swing.JLabel labelCavalo3;
    private javax.swing.JLabel labelCavalo4;
    private javax.swing.JLabel labelPista;
    // End of variables declaration//GEN-END:variables
}
